# Generated by Django 4.2.4 on 2023-11-09 03:04

import bring_u.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id_business', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('desc', models.CharField(max_length=100)),
                ('opening_time', models.TimeField(default='07:00:00')),
                ('closing_time', models.TimeField(default='18:00:00')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('fk_id_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bring_u.business')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id_request', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('status', models.CharField(default='Sin tomar', max_length=30)),
                ('delivery_location', models.CharField(max_length=250)),
                ('desc_delivery', models.CharField(max_length=1000, null=True)),
                ('pick_up_location', models.CharField(default='Pick-up location', max_length=250)),
                ('desc_pick_up_location', models.CharField(max_length=1000, null=True)),
                ('file', models.FileField(null=True, upload_to=bring_u.models.upload_to)),
                ('business_name', models.CharField(max_length=70, null=True)),
                ('fk_id_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bring_u.product')),
                ('fk_id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id_delivery', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField(auto_now=True)),
                ('finished', models.BooleanField(default=False)),
                ('fk_id_client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='client_deliveries', to=settings.AUTH_USER_MODEL)),
                ('fk_id_delivery_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_man_deliveries', to=settings.AUTH_USER_MODEL)),
                ('fk_id_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bring_u.request')),
            ],
        ),
    ]
