# Generated by Django 4.2.4 on 2023-11-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bring_u', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.ImageField(default='food.png', upload_to='uploads/'),
        ),
    ]
