# Generated by Django 4.2.4 on 2023-08-30 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bring_u', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id_business', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('desc', models.CharField(max_length=100)),
                ('opening_time', models.TimeField(default='07:00:00')),
                ('closing_time', models.TimeField(default='18:00:00')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('fk_id_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bring_u.business')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id_request', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('delivery_location', models.CharField(max_length=250)),
                ('fk_id_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bring_u.product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50)),
                ('is_service_prov', models.BooleanField()),
                ('email', models.CharField(max_length=60)),
                ('tel', models.IntegerField()),
                ('profile_pic', models.BinaryField()),
            ],
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Restaurants',
        ),
        migrations.AddField(
            model_name='request',
            name='fk_id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bring_u.user'),
        ),
    ]
