# Generated by Django 4.2.4 on 2023-11-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bring_u', '0002_business_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='file',
            field=models.FileField(null=True, upload_to='orders_media'),
        ),
    ]
