# Generated by Django 4.2.4 on 2023-09-12 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bring_u', '0003_request_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='fk_id_business',
        ),
    ]
