# Generated by Django 4.2.4 on 2023-09-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bring_u', '0003_alter_business_id_business_alter_product_id_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='123', max_length=50),
        ),
    ]
