# Generated by Django 4.2.4 on 2023-09-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bring_u', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='desc_delivery',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='desc_pick_up_location',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='pick_up_location',
            field=models.CharField(default='Pick-up location', max_length=250),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default='Sin tomar', max_length=30),
        ),
    ]
