# Generated by Django 4.2.4 on 2023-09-23 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bring_u', '0005_request_business_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id_delivery', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField(auto_now=True)),
                ('status', models.CharField(default='Tomado', max_length=30)),
                ('fk_id_delivery_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fk_id_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bring_u.request')),
            ],
        ),
    ]
