# Generated by Django 4.2.4 on 2023-09-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bring_u', '0005_request_desc_delivery_request_desc_pick_up_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='fk_id_product',
            new_name='fk_id_business',
        ),
    ]
