# Generated by Django 4.2.4 on 2023-09-11 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_delete_user'),
        ('bring_u', '0006_rename_fk_id_product_request_fk_id_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='fk_id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
