# Generated by Django 4.2.4 on 2023-09-24 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bring_u', '0006_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='fk_id_client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='client_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='fk_id_delivery_man',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_man_deliveries', to=settings.AUTH_USER_MODEL),
        ),
    ]
