# Generated by Django 4.2.4 on 2023-09-24 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bring_u', '0007_delivery_fk_id_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='status',
        ),
    ]
