# Generated by Django 4.2.4 on 2023-09-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('is_service_prov', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=60)),
                ('tel', models.IntegerField()),
                ('profile_pic', models.BinaryField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
