# Generated by Django 4.2.4 on 2023-11-15 07:40

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='photoprofile.jpg', null=True, upload_to=accounts.models.upload_to),
        ),
    ]
