# Generated by Django 4.2.4 on 2023-09-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('is_service_prov', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('tel', models.IntegerField()),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(default='123', max_length=50)),
                ('profile_pic', models.BinaryField()),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
