# Generated by Django 4.2.4 on 2023-09-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(default='123', max_length=50)),
                ('is_service_prov', models.BooleanField()),
                ('email', models.CharField(max_length=60)),
                ('tel', models.IntegerField()),
                ('profile_pic', models.BinaryField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
