# Generated by Django 4.2.4 on 2023-09-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userprofile_options_alter_userprofile_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_service_prov',
            field=models.BooleanField(default=False),
        ),
    ]
