# Generated by Django 4.2.4 on 2023-10-30 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='finish_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
