# Generated by Django 4.2.4 on 2023-11-09 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_finish_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='finish_delivery',
        ),
    ]
